version = "3.11.1"
runner.dialect = scala213

preset = defaultWithAlign
maxColumn = 150
trailingCommas = preserve
newlines.source = keep
align.tokens =  [
                    caseArrow,
                    { code = "extends", owner = "Defn.(Class|Trait|Object)" }
                    { code = "//", owner = ".*" }
                    { code = "{", owner = "Template" }
                    { code = "}", owner = "Template" }
                    { code = "%", owner = applyInfix }
                    { code = "%%",owner =  applyInfix }
                    { code = "%%%",owner =  applyInfix }
                    { code = "<-", owner = "Enumerator.Generator" }
                    { code = "←", owner = "Enumerator.Generator" }
                    { code = "->", owner = applyInfix }
                    { code = ",", owner = "Tuple" }
                    { code = "→", owner = applyInfix }
                    { code = "=", owner = "(Enumerator.Val|Defn.(Va(l|r)|Def|Type))" }
                ]
